import { ArrowRight, Database, Mic2, ScanLine, Server, Sparkles } from "lucide-react";
import { ButtonLink, Panel, Shell, Stat, StatusPill, TopNav } from "@/components/ui";
import { computeMetrics } from "@/lib/demo";
import { formatCurrency } from "@/lib/utils";

export default function Home() {
  const metrics = computeMetrics();

  return (
    <Shell>
      <TopNav />
      <section className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-stretch">
        <div className="border border-line bg-ink/65 p-6 shadow-glow md:p-10">
          <StatusPill>AI Agent Olympics MVP</StatusPill>
          <h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[0.96] tracking-tight text-fog md:text-7xl">
            Booth conversations become qualified revenue.
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-fog/70">
            BoothPilot listens with Speechmatics, identifies visitors with Gemini vision, qualifies leads with Gemini
            reasoning, and stores the CRM workflow on Vultr.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <ButtonLink href="/capture">
              Start Demo <ArrowRight className="ml-2 h-4 w-4" />
            </ButtonLink>
            <ButtonLink href="/command-center" intent="ghost">
              View Agent Trace
            </ButtonLink>
          </div>
        </div>
        <Panel title="Sponsor Stack" eyebrow="Built to win">
          <div className="space-y-4">
            {[
              ["Vultr", "Frontend, backend, Postgres, transcripts, CRM state, and agent logs.", Server],
              ["Speechmatics", "Upload and live-recorded audio transcription with diarization.", Mic2],
              ["Gemini", "Badge OCR, BANT qualification, strategy, and follow-up generation.", Sparkles],
              ["PostgreSQL", "Persistent system of record for every lead and agent step.", Database],
              ["Multimodal", "Audio plus image input creates the visible demo moment.", ScanLine]
            ].map(([name, text, Icon]) => (
              <div key={name as string} className="flex gap-4 border border-line bg-field/60 p-4">
                <Icon className="mt-1 h-5 w-5 text-signal" />
                <div>
                  <p className="font-semibold text-fog">{name as string}</p>
                  <p className="text-sm leading-6 text-fog/60">{text as string}</p>
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </section>

      <section className="mt-6 grid gap-4 md:grid-cols-4">
        <Stat label="Captured Pipeline" value={formatCurrency(metrics.estimatedPipeline)} note="Visible formula, not magic" />
        <Stat label="Hot Leads" value={String(metrics.hot)} note="Ready for sales action" />
        <Stat label="Follow-ups" value={String(metrics.followupsGenerated)} note="Generated by agent" />
        <Stat label="Lost Revenue Prevented" value={formatCurrency(metrics.lostRevenuePrevented)} note="Hot leads without manual follow-up" />
      </section>
    </Shell>
  );
}
